import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

const Home: NextPage = () => {
  return (
    <div className="px-8">
        <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-1 flex-col justify-center items-center min-h-screen py-16">
        <h1 className="text-[#0070f3] no-underline hover:underline focus:underline active:underline text-6xl text-center">
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className="text-center my-16 text-2xl">
          Get started by editing{" "}
          <code className="p-3 rounded-md text-lg bg-gray-200">
            pages/index.tsx
          </code>
        </p>

        <div className="flex items-center justify-center flex-wrap max-w-[800px]">
          <a
            href="https://nextjs.org/docs"
            className="m-4 p-6 text-left no-underline border border-[#eaeaea] rounded-xl max-w-[300px] transition-colors hover:text-[#0070f3] hover:border-[#0070f3] focus:text-[#0070f3] focus:border-[#0070f3] active:text-[#0070f3] active:border-[#0070f3]"
          >
            <h2 className="mb-4 text-2xl">Documentation &rarr;</h2>
            <p className="text-xl">
              Find in-depth information about Next.js features and API.
            </p>
          </a>

          <a
            href="https://nextjs.org/learn"
            className="m-4 p-6 text-left no-underline border border-[#eaeaea] rounded-xl max-w-[300px] transition-colors hover:text-[#0070f3] hover:border-[#0070f3] focus:text-[#0070f3] focus:border-[#0070f3] active:text-[#0070f3] active:border-[#0070f3]"
          >
            <h2 className="mb-4 text-2xl">Learn &rarr;</h2>
            <p className="text-xl">
              Learn about Next.js in an interactive course with quizzes!
            </p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/master/examples"
            className="m-4 p-6 text-left no-underline border border-[#eaeaea] rounded-xl max-w-[300px] transition-colors hover:text-[#0070f3] hover:border-[#0070f3] focus:text-[#0070f3] focus:border-[#0070f3] active:text-[#0070f3] active:border-[#0070f3]"
          >
            <h2 className="mb-4 text-2xl">Examples &rarr;</h2>
            <p className="text-xl">
              Discover and deploy boilerplate example Next.js projects.
            </p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className="m-4 p-6 text-left no-underline border border-[#eaeaea] rounded-xl max-w-[300px] transition-colors hover:text-[#0070f3] hover:border-[#0070f3] focus:text-[#0070f3] focus:border-[#0070f3] active:text-[#0070f3] active:border-[#0070f3]"
          >
            <h2 className="mb-4 text-2xl">Deploy &rarr;</h2>
            <p className="text-xl">
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className="flex flex-1 py-8 border border-[#eaeaea] items-center justify-center">
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
          className="flex justify-center items-center flex-grow"
        >
          Powered by{" "}
          <span className="h-4 ml-2">
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
